version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: 'on-failure'
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - postgres
    networks:
      - serve
    env_file:
      - .env
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - serve
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - serve
    ports:
      - 8080:8080
volumes:
  postgres:
    driver: local
networks:
  serve: